version: '3'

services:
  db:
    image: 
      postgres:10
    
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: always
    
    ports:
      - "5432:5432"
    
  web:
    build: .
    command: python3 manage.py runserver 0.0.0.0:80
    volumes:
      - .:/code
    ports:
      - "80:80"
    depends_on:
      - db
    
volumes:
  db_data:
  
