# Generated by Django 2.0 on 2018-09-12 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('league_code', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_order', models.IntegerField()),
                ('is_home_match', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_id', models.IntegerField()),
                ('point_team1', models.IntegerField()),
                ('point_team2', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season_code', models.DateTimeField(blank=True)),
                ('matches', models.ManyToManyField(to='games.Match')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_order', models.IntegerField()),
                ('name', models.CharField(max_length=40, unique=True)),
                ('alias', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='match',
            name='result_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.Result'),
        ),
        migrations.AddField(
            model_name='match',
            name='team_id',
            field=models.ManyToManyField(to='games.Team'),
        ),
        migrations.AddField(
            model_name='league',
            name='matches',
            field=models.ManyToManyField(to='games.Match'),
        ),
    ]
