# Generated by Django 2.0 on 2018-09-12 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='result',
            old_name='result_id',
            new_name='result_order',
        ),
    ]
