# Generated by Django 2.1.1 on 2018-09-08 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='match',
            old_name='teams',
            new_name='teams_id',
        ),
    ]
