# Generated by Django 2.1.1 on 2018-09-09 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_auto_20180908_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='stadium',
            field=models.CharField(max_length=20),
        ),
    ]
