# Generated by Django 2.1.1 on 2018-09-11 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_auto_20180909_0010'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fixture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_order', models.IntegerField(default=0)),
                ('match_date', models.DateTimeField(blank=True)),
                ('result', models.IntegerField(default=0)),
                ('team_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='games.Team')),
            ],
            options={
                'ordering': ('team_id',),
            },
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField()),
                ('team_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='games.Team')),
            ],
        ),
        migrations.RemoveField(
            model_name='choice',
            name='question',
        ),
        migrations.RemoveField(
            model_name='goal',
            name='scorer_id',
        ),
        migrations.RemoveField(
            model_name='match',
            name='teams_id',
        ),
        migrations.RemoveField(
            model_name='player',
            name='team_id',
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Goal',
        ),
        migrations.DeleteModel(
            name='Match',
        ),
        migrations.DeleteModel(
            name='Player',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
