# Generated by Django 2.1.1 on 2018-09-11 14:22

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_auto_20180911_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='season',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 11, 14, 22, 35, 693316, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='season',
            name='start_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 9, 11, 14, 22, 35, 693276, tzinfo=utc)),
        ),
    ]
