# Generated by Django 2.1.1 on 2018-09-12 01:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0006_auto_20180911_1422'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='location',
            new_name='alias',
        ),
        migrations.RemoveField(
            model_name='team',
            name='stadium',
        ),
        migrations.AlterField(
            model_name='season',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 12, 1, 0, 42, 615051, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='season',
            name='start_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 9, 12, 1, 0, 42, 615008, tzinfo=utc)),
        ),
    ]
