# Generated by Django 2.0 on 2018-09-12 11:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0008_auto_20180912_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='season',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 12, 11, 50, 43, 145942, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='season',
            name='start_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 9, 12, 11, 50, 43, 145899, tzinfo=utc)),
        ),
    ]
